### ISSUE TITLE
Free Applicative

### ISSUE THREAD

**Issue by pakoito** [kategory/kategory#164]
I need to start a discussion before continuing with the implementation, as cats has recently done a refactor-overhaul themselves. The new version is stack-safe, performs better, and reads worse than anything else in our repo.

Reasoning for refactor: https://github.com/typelevel/cats/issues/1151#issuecomment-303226212

PR: https://github.com/typelevel/cats/pull/1748

Implementation: https://github.com/typelevel/cats/commit/693f45687429b22b1d8fba71eb827cfa83662192#diff-19bafa82f16b79d5e02c62e0d1612d28R39

The scalaz counterpart: https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/FreeAp.scala

**Comment by raulraja** [comment]
I think that if the new version by Edmund in Scala is stack-safe that is more important than the implementation readability and ours should resemble that one instead of the previous one. Kategory is a general purpose library that is ment to serve as companion to the stdlib stack-safety and performance is a concern most of our users are going to care and impure and dirty impls to achieve that is a fair trade-off because : FP in the JVM xD
