### ISSUE TITLE
Eliminate some of the syntactic options of for comprehensions

### ISSUE THREAD

**Issue by pakoito** [kategory/kategory#39]
As per #31 there are three possible approaches to comprehensions:

```
optionMonad.binding {
  val a = bind { monad }
  val b = monad.bind()
  val c = ! monad
  yields { a + b + c }
}
```

After the library has been in prod, and if widespread, consider elimination at least one of the options based off usage.

**Comment by raulraja** [comment]
I believe the time has come. I personally think `!` is ambiguous when placed in expressions that may return boolean bound in the kind since it will not negate them.
I believe the saner option is `op.bind()` an is consistent with `op.await()` and other idioms Kotlin users are already familiar with. @pakoito @ffgiraldez Thoughts?

**Comment by pakoito** [comment]
I'd remove !, keep both bind as they're not ambiguous at the moment.
