### ISSUE TITLE
Add Trampoline

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [kategory/kategory#78]

**Comment by pakoito** [comment]
Description from #77 

>Trampoline is often used to emulate tail recursion. The idea is to have some step code that can be trampolined itself to emulate recursion. The difference with standard recursion would be that there is no need to rewind the whole stack when we reach the end of the stack, since the first value returned that is not a trampoline would be directly returned as the overall result value for the whole function chain. That means Trampoline emulates what tail recursion does.

There are languages that do not have tailrec modifier that use Trampoline to emulate the same behavior. But Trampoline is also useful for languages that also have trampolines out of the box:

"As long as you use tail recursion with one function everything is fine as the compiler will optimize it for you and transform it in a loop, issues come when you are trying to use tail recursive calls between two functions or when you don’t have a tail recursive call."

Trampolines are stack safe, since they do not need to maintain a function call stack (since they don't need to rewind it). So trampolines are useful also when you don't want to blow your stack up for too long recursive operations.
